version: '3'
services:
  app:
    image: ghcr.io/hideki0403/aira:latest
    build:
      context: .
      args:
        - enable_mecab=1
    volumes:
      - './config.yaml:/aira/config.yaml:ro'
      - './fonts:/aira/fonts:ro'
      - './data:/aira/data'
    restart: always
