version: '3'
services:
  app:
    build:
      context: .
      args:
        - enable_mecab=1
    platform: linux/amd64
    volumes:
      - './config.yaml:/aira/config.yaml:ro'
      - './fonts:/aira/fonts:ro'
      - './data:/aira/data'
    restart: always
